import Head from 'next/head'
import ProductPage from "./productPage";

export default function Home() {
    return (<>
            <Head>
                <title>Flowers in Ukraine</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <div>
                <ProductPage/>
            </div>
        </>)
}
